### ISSUE TITLE
Do you need this controller at all?

### ISSUE THREAD

**Issue by dummied** [Bulldogse45/LeagueKit#114]
https://github.com/Bulldogse45/LeagueKit/blob/master/app/controllers/announcement_vieweds_controller.rb

**Comment by dummied** [comment]
Um. That's not the controller I had in mind ... I suspect you need that one ...

**Comment by Bulldogse45** [comment]
"I don't need to check it.  I am deleting an empty file"- Matt Fair Jan 7, 2016.  Never again.

**Comment by Bulldogse45** [comment]
Also, THANKS!!
