### ISSUE TITLE
Suspect this doesn't work as you expect

### ISSUE THREAD

**Issue by dummied** [Bulldogse45/LeagueKit#120]
https://github.com/Bulldogse45/LeagueKit/blob/master/app/controllers/teams_controller.rb#L14

**Comment by Bulldogse45** [comment]
I am not sure what you mean by this

**Comment by dummied** [comment]
When would a team have an id of "original_id"?

**Comment by Bulldogse45** [comment]
it is checking the column original_id.  It is checking if it is the original team or one of the "clone" teams.  If the id = original_id it is the original team.  It seems to be working.

**Comment by dummied** [comment]
Ah. Carry on then.
